export const EXCEL_TABLE_COLUMNS = [
  'Account #',
  'Company Name',
  'Trading As',
  'Formerly',
  'Group',
  'Area',
  'Sector',
  'Vat #',
  'Other Names On Cheques',
  'Description',
  'Actual',
  'Reason',
  'Status',
  'Contract #',
  'Contract Date',
  'License',
  'License Basic USD',
  'License Detail',
  'Added %',
  'Gross',
  'Net',
  'Vat',
  'Comment',
  'Ceo Name',
  'Ceo Email',
  'Ceo Phone',
  'Ceo Fax',
  'Address',
  'Tel',
  'Fax',
  'Cell',
  'Accountant Name',
  'Accountant Email',
  'Box City',
  'Box #',
  'Box Area',
  'Delivery City',
  'Delivery Address',
  'Delivery Suburb',
  'Databases',
  'Operators',
] as const;

// const ExcelTableColumnSchema
