export const AppLinks = {
  Home: '/',
  Login: '/login',
  Logout: '/logout',
  Join: '/join',
  MyAccount: '/my-account',
  PickLists: '/pick-lists',
  AuditTrails: '/audit-trails',
  CustomerCare: '/customer-care',
  Customers: '/customers',
  Customer: (id: number) => `/customers/${id}`,
  EditCustomer: (id: number) => `/customers/${id}/edit`,
  DeleteCustomer: '/delete-customer',
  AddCustomer: '/customers/create',
  Import: '/customers/import',
  Backup: '/customers/backup',
  Users: '/users',
  AddUser: '/users/create',
  AuditTrail: '/audit-trail',
};
